### PR TITLE
Fix Bug in AWK, & Address a Bunch of Stuff

### PR DESCRIPTION
**Pull request by ghost**
Hope these help. Let me know if there are any issues at all.

### CODE REVIEW

**Comment by ghost** [comment]
Lol "ANSCII" ... ANSII + ASCII ... yep.

**Comment by bing0o** [comment]
domains_Error
this is the first error :D, it needs to escape the special chars, also i want to mention the line 76 
`awk -F'"' '{gsub("*.", "", $4);` 
it needs to be like that
`awk -F'"' '{gsub(/\*\./, "", $4);`

everything else looks fine :D

**Comment by ghost** [comment]
Quite right! My bad, I forgot about the `//` in AWK. I'll sort that and the other thing in a bit. Might not be doing as much today, as I'm not feeling great; hopefully not Corona Virus. -_-

**Comment by bing0o** [comment]
oh man, take care of yourself first , the world still waiting a lot from you :), i hope you'll get well soon :D .
don't worry about that script, fix when you get better, and find yourself free.
thank you so much :heart: :smile:

**Comment by terminalforlife** [comment]
Thanks! But I'll go nuts if I sit at home and twiddle my thumbs, so I'm more than happy to help when I can. :)

**Comment by terminalforlife** [comment]
Working on those conflicts now.

I'm trying to understand (plus I'm curious) the use of _crt.sh_, which BTW looks like a really cool website. Is it by Chubin? I know he/she has a few cool projects like that, such as _cheat.sh_ and _wttr.in_.

The URL you're using `https://crt.sh/?q=%.$domain&output=json&exclude=expired` has `%.` in the query; why is that? Some sort of glob-like effect to matching anything before the domain name?

**Comment by ghost** [comment]
Closing pull request, because it's not even remotely ready yet. My bad. Hopefully be done tomorrow.

**Comment by bing0o** [comment]
it's ok man, take your time, i just took a look at the code and it looks great as always u do, i dont know why u closed it, anyway I'm gonna update [encall.sh](https://github.com/bing0o/bash_scripting/blob/master/encall.sh) if you remember it, just some lil changes to make it more productive

**Comment by ghost** [comment]
Thanks. :) I rememeber `encall.sh`! Good times. Lol

I closed the PR because it was left in a pretty sorry state, with bugs everywhere. I've actually been working on a little something which I think you might like. You inspire me quite often. It's early in development and a bit buggy, but [Dominator](https://github.com/terminalforlife/PerlProjects/tree/master/source/dominator) is the program.

**Comment by bing0o** [comment]
hey man, I'm really glad to hear that :D, i'm really happy to see that my scripts is being useful or at least not useless ^^!, especially for someone i'm learning from :), I will go deeper with bash next days :+1:

**Pull request closed without merging**
