### PR TITLE
Improve Portability of and Optimize `monitor.sh`

### PR DESCRIPTION
**Pull request by ghost**
I've also made it so `encall.sh` will no longer assume the user is specifying files in the current directory; it was part of the old way the file worked, but I guess is no longer relevant. You merged my PR before I had I chance to fix that one. lol

Regarding `monitor.sh`, it's just a lot more portable. Fewer external tools or additional processes are needed. There's also a dependency check. I figure that this is a script which is polled; executed every so often.

It would be handy to have this (`monitor.sh`) script in a loop, the iteration interval for which could be set by the user or something. Essentially, the script would then act like a daemon. What do you think?

I did a similar thing [here](https://github.com/terminalforlife/Extra/blob/master/source/feh-slides), although it's not daemon-like, because it doesn't wait for input; I guess you could say it waits for new backgrounds, since you could change them on-the-fly.

### CODE REVIEW

**Comment by bing0o** [comment]
it's ok you can make the changes that you need on `encall.sh` and i will merge the pull request , 
about `monitor.sh`, at the first i used to create a startup process and give it this command 
```bash
/bin/bash -c "sleep 15 && while true; do <your path to bash script, ex: /home/user/monitor.sh> ; sleep 300; done"
```
which means the script is gonna be run every 5 minutes, something like what you've mentioned .
but also crontab will works fine i think,
i tried the update and it's working well.
do you have any additional updates or ideas !?, or i just merge the pull request ?.
keep it up man :) .

**Comment by ghost** [comment]
Awesome. Don't merge yet, then. I'll see if I can squeeze anything else out of my brain. lol

**Comment by bing0o** [comment]
@terminalforlife okay have a great time :D

**Comment by ghost** [comment]
Sorry I never got back to you. :( For shame. If you'd still like to merge, you're more than welcome to.

**Comment by bing0o** [comment]
I'm very happy with your modifications i got better with bash scripting because of it , thanks a lot ^^.

i hope you won't stop it, keep it up :)

**Comment by ghost** [comment]
Awesome! I'm really glad my stuff helped you. I have no intention of quitting with Shell programming, because it's part of everything I do in Linux, and I have a ton of Shell projects I have to maintain, such as Cito, so I'm stuck with it. :D

**Comment by bing0o** [comment]
that's good, BTW i saw your cito project it's really cool, great job, 

have a good time :smile:

**Comment by ghost** [comment]
Thank you! There are a couple of bugs I still need to iron out, but I've been spending a LOT of time and energy working on [UbuChk](https://github.com/terminalforlife/PerlProjects/tree/master/source/ubuchk).

Also finding myself interested in JavaScript and Lua, but they both pale in comparison to a combination of Perl and Shell, at least for me and what I want out of a programming language.

**Comment by bing0o** [comment]
i saw that on your youtube channel, also i watched the video about UbuChk, it's huge man, gonna try it after i figure out how to install cito :D, cuz it didn't work, i run the installation command but nothing happen

**Comment by ghost** [comment]
Much appreciated.

What went wrong with the installation command? I need to fix that if something went wrong. lol If you could post the output here you get when trying to install it, that would help a lot.

I wrote you a [present](https://github.com/terminalforlife/Extra/blob/dev/source/narc) today. :) I hope I did it justice. I may have gone all out there. lol Let me know if it works, if you'd like to use it, so I can push it to master. No obligation to use it, I just wanted to do something nice. Lol

**Comment by bing0o** [comment]
i did it , i installed cito , gonna try `UbuChk` , i'll give a feedback :)
your present is very cool, thanks a lot , but there's some errors
on line 140 it should ends with `; then`
also when you put the -d argument for the domain it still asks to enter the domain!
but everything else looks great , i hope u will fix it so we can use it ^^, 
BTW i have some updates for `autorecon.sh`, i added some other tools to generate more information about the target domain!

**Comment by ghost** [comment]
Okidoke! :D Glad you like it. I'll fix the errors and try to incorporate your changes; it'll probably have to be tomorrow, as it's really late here now.

Glad you got Cito installed, but I urge you to reinstall it. Lol I just got done fixing it up. But note that in the new version, files will always be overwritten if they already exist.

What went wrong with the installation of Cito beforehand, though?

I love Cito and am proud of it, but sometimes I miss Insit. lol Dunno if you were around back then, but Insit (formerly Installit) was the OG of my installers.

**Comment by bing0o** [comment]
yea , I installed the new version already, it was my mistake when the installation failed last time, i did it wrong ^^! 
please if you have a lil of free time, take a look at this script [domains.sh](https://github.com/bing0o/bash_scripting/blob/master/domains.sh) , I think my bash skills is in another level :D

**Comment by ghost** [comment]
Just had a look. Nice one. Some things I'd address:

* Redundant use of cat(1) on line 186. (better as: `sort [FILE]`)
* Double-negative logic on line 166. (better as: `CONDITION || ...`)
* Excessive one-liners hampering readability.
* Regarding portability, `printf` is preferred.
* On lines 122 & 132, you're better off with Bash's own syntax (`${use//,/ }`)
* Lines 53, 59, and 65 have a lot of extra processing where not needed. Look into AWK's other features, because it can replace your uses of sed(1), grep(1), and tr(1). Particularly, you'll want to look at AWK's `sub()` and `gsub()` functions.
* Line 187 you have wc(1) used as `$(wc -l $out)`, which will include filename. You could use `$(wc -l < $out)` as a trick to omit the filename, if that's what you're after.

It's really nice to see how you've improved over time. :)

I noticed you've got "\@hack1lab" on the ANSI-art thing; what's that? Piqued my curiosity. lol

**Comment by bing0o** [comment]
@terminalforlife thank you soo much :heart: :smile: 
1- fixed :heavy_check_mark: 
2- i think it's right because if the user used both of `-u` and `-e`, it's not correct, that's why i check for them both, to display the Error message!
3- you're right but, I have nothing to do with that, cuz i need to filter the results, using `awk`, `grep` .. etc.
4- yea that's right `printf` is better in bash, do i need to change all of the `echo` with `printf` ?
5- fixed :heavy_check_mark: 
6- I couldn't make it, since i use -F/ to split the results and gsub() deal with the original result not the splitted one, if there any way to do that please tell me.
7- actually i needed it this way to display the file name :)

thanks again :D

**Comment by bing0o** [comment]
I figured it out, i could replace `sed` in `awk` using `gsub()`

**Comment by ghost** [comment]
Yep, that's what I was getting at. :D Because `sub()` is a single replacement, whereas `gsub()` is global.

And regarding `grep` functionality within `awk`, you can use, for example:

```
awk '/MATCH/ {print($1)}' [FILE]
```

**Comment by bing0o** [comment]
done :+1: , thank you so much
but in line 65 `awk -F, '{/$domain/ gsub("\"", "", $2); print $2}'` it didn't work since i grep for a $domain variable and it's not working inside `''`

**Comment by ghost** [comment]
Yeah, I fixed that in my PR. Go check it. xD

**Comment by bing0o** [comment]
done :heavy_check_mark: , let's fix the issues :D.

**Pull request merged**
